// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.agh.odis.domain;

import org.springframework.beans.factory.annotation.Configurable;
import pl.agh.odis.domain.UserData;

privileged aspect UserData_Roo_Configurable {
    
    declare @type: UserData: @Configurable;
    
}
